import numpy as np
print("=== 杩蜂綘 Transformer 鏋舵瀯 ===\n")
print("杈撳叆 鈫?浣嶇疆缂栫爜 (+) 鈫?)
print("  Encoder:")
print("    Self-Attention 鈫?Add&Norm 鈫?)
print("    FeedForward  鈫?Add&Norm 鈫?)
print("  Decoder:")
print("    Masked-Self-Attn 鈫?Add&Norm 鈫?)
print("    Cross-Attention  鈫?Add&Norm 鈫?)
print("    FeedForward      鈫?Add&Norm 鈫?)
print("  杈撳嚭灞?Linear + Softmax)")
print("\n鏍稿績鍒涙柊: 骞惰澶勭悊 + 鍏ㄥ眬渚濊禆")
