print("=== Transformer 变体 ===\n")
print("BERT (Bidirectional):")
print("  只看 Encoder, 双向注意力")
print("  适合: 文本分类、NER、问答\n")
print("GPT (Generative):")
print("  只看 Decoder, 单向(因果)注意力")
print("  适合: 文本生成、对话\n")
print("其他变体:")
print("  T5: Encoder-Decoder 全文")
print("  ViT: Transformer 用于图像")
print("  Whisper: Transformer 用于语音")
