print("=== Transformer 鍙樹綋 ===\n")
print("BERT (Bidirectional):")
print("  鍙湅 Encoder, 鍙屽悜娉ㄦ剰鍔?)
print("  閫傚悎: 鏂囨湰鍒嗙被銆丯ER銆侀棶绛擻n")
print("GPT (Generative):")
print("  鍙湅 Decoder, 鍗曞悜(鍥犳灉)娉ㄦ剰鍔?)
print("  閫傚悎: 鏂囨湰鐢熸垚銆佸璇漒n")
print("鍏朵粬鍙樹綋:")
print("  T5: Encoder-Decoder 鍏ㄦ枃")
print("  ViT: Transformer 鐢ㄤ簬鍥惧儚")
print("  Whisper: Transformer 鐢ㄤ簬璇煶")
